### PR TITLE
Backend blog

### PR DESCRIPTION
**Pull request by Megh-Thakkar**
Pull request containing the details of the framework to be used as well as to track the progress of the project.

### CODE REVIEW

**Comment by DennisSchwartz** [comment]
Looks good!
Just as a small tip: It looks like the blog post from PR #7 is also part of this pull request. If you branch from master we can keep them separated and don't have to worry about the order that we merge them in.

**Comment by Megh-Thakkar** [comment]
@DennisSchwartz yes I realized this as soon as I read your comment in the other PR. Once this is approved, I will branch from this repo itself and make the necessary changes for the further progress.

**Comment by DennisSchwartz** [comment]
@rowlandm Do we still need these changes?
@Megh-Thakkar Can you make the changes that Rowland requested? Then we can merge it after :)

**Comment by rowlandm** [comment]
Let's merge it as is.

**Comment by Megh-Thakkar** [comment]
Added information about how the cron job would be working as discussed on this week's call. @sarthak-sehgal review this once. Will merge it.

**Comment by rowlandm** [comment]
You didn't mention the change to Django in the post. Will you do it to another PR or this one?

**Comment by Megh-Thakkar** [comment]
@rowlandm I will add that in about an hour. Merging this right now. Thanks.

**Pull request merged**
