### PR TITLE
Backend blog

### PR DESCRIPTION
**Pull request by Megh-Thakkar**
1. Blog post for backend project- Week 4
2. Updated management command in previous blog post after modifications.

### CODE REVIEW

**Comment by sarthak-sehgal** [comment]
@Megh-Thakkar @rowlandm Do we need the codes in the blog post, though? The tests section.

**Comment by Megh-Thakkar** [comment]
@sarthak-sehgal bit difficult to "show" backend :smile:

**Comment by rowlandm** [comment]
No need for putting code in the blog. Its just a quick summary.

**Comment by Megh-Thakkar** [comment]
@rowlandm the reason I put code snippets is that the readers will not have to juggle between Github and the blog, if they wished  to go through an implementation.

**Comment by rowlandm** [comment]
Its too detailed Megh.

The code reviews demonstrate that your code is easy to read and follow.

What people need in the blog is a high level overview, not details.

Students tend to go into details when they should be summarising.

**Comment by Megh-Thakkar** [comment]
Ohh. ohkay! I will surely keep that in mind for the upcoming blog posts! :smile:

**Comment by rowlandm** [comment]
No worries.

**Pull request merged**
